fix: :bug: Update yml for incorrectly defined directories

diff --git a/.github/workflows/createProduct-ci-cd.yml b/.github/workflows/createProduct-ci-cd.yml
--- a/.github/workflows/createProduct-ci-cd.yml
+++ b/.github/workflows/createProduct-ci-cd.yml
@@ -3,11 +3,11 @@ name: Docker Image CI/CD for Product Service - Create
 on:
   push:
     paths:
-      - 'catalog/readProductService/**'
+      - 'catalog/createProductService/**'
     branches: ["test"]
   pull_request:
     paths:
-      - 'catalog/readProductService/**'
+      - 'catalog/createProductService/**'
     branches: ["QA", "main"]
 
 jobs:
@@ -29,16 +29,16 @@ jobs:
     # Paso 3: Construir la imagen Docker usando los secrets
     - name: Build Docker image
       run: |
-        docker build catalog/readProductService/. --file catalog/readProductService/Dockerfile \
+        docker build catalog/createProductService/. --file catalog/createProductService/Dockerfile \
           --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
           --build-arg DB_NAME=${{ secrets.DB_NAME }} \
           --build-arg SERVER_PORT=${{ secrets.SERVER_PORT_CREATE_PRODUCT }} \
-          -t ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
+          -t ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
 
     # Paso 4: Subir la imagen a Docker Hub
     - name: Push Docker image to Docker Hub
       run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
+        docker push ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
 
   deploy:
     needs: build
@@ -63,18 +63,30 @@ jobs:
             sudo usermod -a -G docker ec2-user
           fi
 
+          # Detener y eliminar el contenedor previo si existe
           echo "Deteniendo y eliminando contenedor previo..."
-          sudo docker stop read-product-service || true
-          sudo docker rm read-product-service || true
+          sudo docker stop create-product-service || true
+          sudo docker rm create-product-service || true
           
+          # Descargar la última imagen desde Docker Hub
           echo "Actualizando imagen desde Docker Hub..."
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
           
-          echo "Ejecutando nuevo contenedor en el puerto 80..."
+          # Ejecutar el nuevo contenedor en el puerto 80
+          echo "Ejecutando nuevo contenedor en el puerto ${{
+            secrets.SERVER_PORT_CREATE_PRODUCT }}..."
           sudo docker run -d \
-            --name read-product-service \
+            --name create-product-service \
             -p 80:${{ secrets.SERVER_PORT_CREATE_PRODUCT }} \
             -e MONGO_URI=${{ secrets.MONGO_URI }} \
             -e DB_NAME=${{ secrets.DB_NAME }} \
             -e SERVER_PORT=${{ secrets.SERVER_PORT_CREATE_PRODUCT }} \
-            ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
+            ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
+
+          # Verificar que el contenedor esté corriendo
+          if sudo docker ps -f name=create-product-service | grep create-product-service; then
+            echo "Contenedor corriendo correctamente."
+          else
+            echo "Error al iniciar el contenedor. Revisa los logs."
+            exit 1
+          fi
