Update login.yml

diff --git a/.github/workflows/login.yml b/.github/workflows/login.yml
--- a/.github/workflows/login.yml
+++ b/.github/workflows/login.yml
@@ -93,20 +93,34 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           port: 22
           script: |
-                # Actualizar y configurar Docker
-                sudo yum update -y
-                sudo yum install -y docker
-                sudo service docker start
-                sudo usermod -a -G docker ec2-user
-              
-                # Descargar la imagen Docker desde DockerHub
-                sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login-service:latest
-              
-                # Detener y eliminar cualquier contenedor existente con el nombre "login-service"
-                if [ $(sudo docker ps -aq -f name=login-service) ]; then
-                  sudo docker stop login-service
-                  sudo docker rm login-service
-                fi
-              
-                # Iniciar un nuevo contenedor con la imagen más reciente
-                sudo docker run -d --name login-service -p 80:80 ${{ secrets.DOCKER_USERNAME }}/login-service:latest
+            # Actualizar y configurar Docker
+            sudo yum update -y
+            sudo yum install -y docker
+            sudo service docker start
+            sudo usermod -a -G docker ec2-user
+          
+            # Descargar la imagen Docker desde DockerHub
+            echo "==> Pulling the latest Docker image"
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login-service:latest
+          
+            # Verificar si el contenedor existe
+            if [ $(sudo docker ps -aq -f name=login-service) ]; then
+              echo "==> Stopping and removing existing container"
+              sudo docker stop login-service || echo "Failed to stop container, possibly not running."
+              sudo docker rm login-service || echo "Failed to remove container, ensure it is stopped."
+            else
+              echo "==> No existing container found with the name 'login-service'"
+            fi
+          
+            # Iniciar un nuevo contenedor con la imagen más reciente
+            echo "==> Starting a new container"
+            sudo docker run -d --name login-service -p 80:80 ${{ secrets.DOCKER_USERNAME }}/login-service:latest
+          
+            # Verificar si el contenedor está corriendo
+            if sudo docker ps -f name=login-service | grep login-service; then
+              echo "==> Container started successfully"
+            else
+              echo "==> Failed to start the container. Check the Docker logs for details."
+              exit 1
+            fi
+
